declare module '*.scss';
declare module '*.svg';
declare module '*.svg?inline';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.bmp';
declare module '*.tiff';
